In [1]:
import gym

In [2]:
env = gym.make('CartPole-v1')
env.reset()
print(env.action_space)
print(env.observation_space.shape)

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Discrete(2)
(4,)


In [215]:
import torch
import torch.nn as nn
import pdb

torch.manual_seed(1)

model = nn.Sequential(
    nn.Linear(4, 8, bias=False),
#     nn.Dropout(p=0.6),
    nn.ReLU(),
    nn.Linear(8, 1, bias=False),
#     nn.Sigmoid(),
)

x = torch.ones(4)
y0 = torch.tensor(7.)

loss_fn = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

optimizer.zero_grad()
for i in range(200):

    y = model(x)
    loss = loss_fn(y, y0)
    
    if loss.item() < 1e-5:
        print(f'after {i} steps')
        break
      
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
print('y:', y)
for label, value in model.state_dict().items():
    print(label)
    print(value)

after 126 steps
y: tensor([6.9988], grad_fn=<SqueezeBackward3>)
0.weight
tensor([[ 0.8411,  0.3628,  0.4865,  0.8181],
        [-0.4707,  0.2999, -0.1029,  0.2544],
        [-0.0641, -0.1948,  0.0051, -0.1089],
        [ 0.1826, -0.1949, -0.0365, -0.0450],
        [ 0.6402,  0.5657,  1.0048,  0.7233],
        [-0.1862, -0.3020, -0.0838, -0.2157],
        [ 0.4406,  0.6248,  0.8989,  0.8726],
        [-0.6859,  0.1128, -0.0575,  0.2771]])
2.weight
tensor([[ 0.8684, -0.3221, -0.2251, -0.1705,  0.9041, -0.0589,  0.7641,  0.0078]])


In [216]:
import torch
import torch.nn as nn
import pdb

torch.manual_seed(1)

model = nn.Sequential(
    nn.Linear(4, 8, bias=False),
#     nn.Dropout(p=0.6),
    nn.ReLU(),
    nn.Linear(8, 1, bias=False),
#     nn.Sigmoid(),
)

x = torch.ones(4)
y0 = torch.tensor(7.)

loss_fn = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

optimizer.zero_grad()
for i in range(5000):

    y = model(x)
    loss = loss_fn(y, y0)
    
    if loss.item() < 1e-5:
        print(f'after {i} steps')
        break
    
    loss.backward()
    
    if(i+1) % 5 == 0:
        optimizer.step()
        optimizer.zero_grad()
        
print('y:', y)
for label, value in model.state_dict().items():
    print(label)
    print(value)  


after 630 steps
y: tensor([6.9988], grad_fn=<SqueezeBackward3>)
0.weight
tensor([[ 0.8411,  0.3628,  0.4865,  0.8181],
        [-0.4707,  0.2999, -0.1029,  0.2544],
        [-0.0641, -0.1948,  0.0051, -0.1089],
        [ 0.1826, -0.1949, -0.0365, -0.0450],
        [ 0.6402,  0.5657,  1.0048,  0.7233],
        [-0.1862, -0.3020, -0.0838, -0.2157],
        [ 0.4406,  0.6248,  0.8989,  0.8726],
        [-0.6859,  0.1128, -0.0575,  0.2771]])
2.weight
tensor([[ 0.8684, -0.3221, -0.2251, -0.1705,  0.9041, -0.0589,  0.7641,  0.0078]])
